1025 check packets

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,8 +11,29 @@ jobs:
           SECOND_NAME: Zhuofan
         run: |
             echo $MY_VAR $FIRST_NAME and $SECOND_NAME .
-  update-dependencies:
+  check-packets:
     runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+      - name: check flask is required
+        run: |
+          if grep -q flask requirements.txt; then
+            echo "Package found in requirements.txt"
+          else
+            echo "Package not found in requirements.txt"
+            exit 1
+          fi
+      - name: check flake8
+        run: pip freeze | grep flake8
+      
+  python-formatting:
+    runs-on: ubuntu-latest
+    needs: check-packets
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -22,16 +43,6 @@ jobs:
           python-version: 3.9
       - name: update pip
         run: python -m pip install --upgrade pip
-  python-formatting:
-    runs-on: ubuntu-latest
-    needs: update-dependencies
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.9
       - name: Install flake8
         run: pip install flake8
       - name: Run flake8
